// Hand-written, NOT generated by the shadcn CLI (unlike every other file in this folder).
// The CLI's version imports `useTheme` from `next-themes`, which this Vite app does not use.
// Do not "regenerate" it.
//
// Styling goes through CSS custom properties passed via `style`, NOT `toastOptions.classNames`.
// Sonner injects its own stylesheet at runtime (`node_modules/sonner/dist/index.mjs`'s
// `__insertCSS` call) whose base rule is:
//   [data-sonner-toast][data-styled=true] { background: var(--normal-bg); border: 1px solid
//   var(--normal-border); color: var(--normal-text); ... }
// That selector's specificity is (0,2,0), which always beats a Tailwind utility class (0,1,0) —
// so a `classNames`-only approach (what an earlier version of this file did) is silently inert;
// none of those classes ever actually applied. Setting the CSS variables sonner itself reads is
// the only mechanism that works, and it keeps the app's own design tokens as the source of truth.
//
// The destructive/error palette additionally requires the `richColors` prop below: sonner's error
// rule is `[data-rich-colors=true][data-sonner-toast][data-type=error] { background:
// var(--error-bg); border-color: var(--error-border); color: var(--error-text) }` — gated behind
// `data-rich-colors=true`, which sonner only ever sets when `richColors` is passed. Without it,
// EVERY toast (including an error) renders with only the `--normal-*` variables, no matter what
// `--error-*` is set to.
//
// This does NOT make dark mode "come for free": sonner's own `theme` prop defaults to `'light'`
// and, when set to `'system'`, follows the OS `prefers-color-scheme` media query — it has no
// awareness of this app's `.dark` class toggle at all. The variables below are set as an inline
// `style` on the `<Toaster>` element, so they win over sonner's `data-sonner-theme` attribute
// regardless of its value; they WILL track a real light/dark toggle if one is ever added, but
// only because their values reference the SAME `--background`/`--foreground`/`--border`/
// `--destructive` tokens the rest of the app uses — not because of anything sonner does itself.
import * as React from 'react';
import { Toaster as SonnerToaster } from 'sonner';

export function Toaster() {
  return (
    <SonnerToaster
      position="bottom-right"
      richColors
      style={
        {
          '--normal-bg': 'hsl(var(--background))',
          '--normal-text': 'hsl(var(--foreground))',
          '--normal-border': 'hsl(var(--border))',
          '--error-bg': 'hsl(var(--background))',
          '--error-text': 'hsl(var(--destructive))',
          '--error-border': 'hsl(var(--destructive))',
        } as React.CSSProperties
      }
    />
  );
}
